"""Canonical serialisation and hashing of an approved handover.

WHAT GOES ONCHAIN: a SHA-256 digest, and a short label of the form
"<patient_id>:<situation>". Nothing else. No claim text, no clinical detail, no
record bodies. The digest is one-way; the chain proves a specific approved
state existed at a specific time and reveals nothing about its content.

Even the label is deliberately minimal: patient ids here are synthetic
identifiers generated by Synthea, never real-world identifiers.

Canonicalisation matters more than it looks. The same approved brief must hash
identically on every machine and every run, or verification is worthless -- so
keys are sorted, claims are ordered deterministically, and the JSON separators
are pinned rather than left to the default (which inserts spaces and would
change the digest).
"""

import hashlib
import json
from typing import Any


def canonical_commitment_payload(patient_id: str, situation: str,
                                 approved_claims: list[dict[str, Any]]) -> dict:
    """The exact, minimal, sorted representation that gets hashed.

    Only the claim text and its gate verdict are included. Two briefs whose
    claims differ only in ordering must produce the same digest, so claims are
    sorted; two briefs whose verdicts differ must not, so the verdict is part
    of the hashed content.
    """
    claims = [
        {"text": str(claim["text"]), "gate_result": str(claim["gate_result"])}
        for claim in approved_claims
    ]
    claims.sort(key=lambda c: (c["text"], c["gate_result"]))
    return {
        "version": 1,
        "patient_id": patient_id,
        "situation": situation,
        "claims": claims,
    }


def canonical_json(payload: dict) -> bytes:
    """Byte-stable JSON. separators are pinned; default spacing would alter
    the digest for identical content."""
    return json.dumps(payload, sort_keys=True, separators=(",", ":"),
                      ensure_ascii=True).encode("utf-8")


def compute_commitment_hash(payload: dict) -> bytes:
    return hashlib.sha256(canonical_json(payload)).digest()


def commitment_label(patient_id: str, situation: str) -> str:
    """Short onchain label. Synthetic identifier only."""
    return f"{patient_id}:{situation}"


def compute_evidence_root(evidence_ids: list[str]) -> bytes:
    """A single digest over the evidence backing an approved brief.

    Sorted before hashing so the same evidence set produces the same root
    regardless of the order claims happened to be resolved in -- otherwise two
    identical approvals would attest to different roots.

    A flat hash of sorted ids, not a Merkle tree. A tree would let someone prove
    one specific piece of evidence was included without revealing the rest;
    nothing in MEMORA needs that today, and building it speculatively would be
    complexity without a caller.
    """
    payload = {"version": 1, "evidence": sorted(set(evidence_ids))}
    return hashlib.sha256(canonical_json(payload)).digest()


def compute_context_hash(situation: str, role: str) -> bytes:
    """A digest of the clinical context an approval was made in.

    Binds an attestation to the situation and role it was reviewed under, so a
    brief approved for an ICU-to-ward handover cannot later be presented as
    having been approved for a pre-operative review.
    """
    payload = {"version": 1, "situation": situation, "role": role}
    return hashlib.sha256(canonical_json(payload)).digest()
