"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { listPatients } from "@/lib/api/client";
import { MemoraApiError, PatientSummaryOut } from "@/lib/api/types";
import { KIND_LABELS } from "@/lib/config/demo-data";
import {
  Badge, Button, Card, EmptyState, IconBadge, Notice, Section, SkeletonList,
} from "@/components/app/ui";

/**
 * Patients actually present in the Sibyl store.
 *
 * Nothing here is hardcoded. Ids are Synthea UUIDs generated per ingestion
 * run, so this list is the only way to learn them — which is also the point
 * worth showing: the app does not know who exists until memory tells it.
 */
export default function PatientsPage() {
  const [patients, setPatients] = useState<PatientSummaryOut[] | null>(null);
  const [error, setError] = useState<MemoraApiError | null>(null);

  useEffect(() => {
    let cancelled = false;
    listPatients()
      .then((list) => !cancelled && setPatients(list))
      .catch((e) => !cancelled && setError(e as MemoraApiError));
    return () => { cancelled = true; };
  }, []);

  return (
    <div className="stack stack--loose">
      <div className="stack stack--tight">
        <h1 className="page-title">Patients</h1>
        <p className="subtle" style={{ margin: 0, maxWidth: 640 }}>
          Read live from the Sibyl store. These ids are generated by Synthea at
          ingestion time — the app has no list of its own and learns who exists
          only by asking memory.
        </p>
      </div>

      {error && (
        <Notice tone={error.code === "sibyl_unavailable" ? "error" : "warn"}
                title={error.code === "sibyl_unavailable"
                  ? "MEMORA cannot reach its memory layer"
                  : "Could not load patients"}>
          {error.detail}
          {error.code === "sibyl_unavailable" && (
            <p style={{ marginBottom: 0, marginTop: 8 }}>
              This is the intended behaviour — without Sibyl the system refuses
              rather than answering from nothing.
            </p>
          )}
        </Notice>
      )}

      {!patients && !error && <SkeletonList rows={3} />}

      {patients?.length === 0 && (
        <EmptyState title="No patients in this store">
          Ingest some first:{" "}
          <code className="mono">
            python scripts/ingest_demo.py ../vendor/synthea/output/fhir 3
          </code>
        </EmptyState>
      )}

      {patients && patients.length > 0 && (
        <Section title={`${patients.length} in memory`}>
          <div className="grid grid--3">
            {patients.map((p) => (
              <Card key={p.patient_id} className="card--hoverable">
                <div className="stack">
                  <IconBadge icon="user" tone="accent" />
                  <div className="stack stack--tight">
                    <span className="mono" style={{ fontSize: 13, color: "var(--text)" }}>
                      {p.patient_id.slice(0, 18)}…
                    </span>
                    <span className="dim">
                      memory version {p.memory_version} · {p.fact_count} facts ·{" "}
                      {p.event_count} events
                    </span>
                  </div>

                  <div className="row" style={{ gap: 6 }}>
                    {p.has_drug_allergy && <Badge tone="review">drug allergy</Badge>}
                    {Object.entries(p.kinds)
                      .sort((a, b) => b[1] - a[1])
                      .slice(0, 4)
                      .map(([kind, n]) => (
                        <Badge key={kind}>
                          {KIND_LABELS[kind] ?? kind} {n}
                        </Badge>
                      ))}
                  </div>

                  <div className="row" style={{ gap: 8 }}>
                    <Link href={`/app/patients/${encodeURIComponent(p.patient_id)}`}
                          className="btn btn--primary btn--sm">
                      Open memory
                    </Link>
                    <Button href={`/app/handoff/new?patientId=${encodeURIComponent(p.patient_id)}`}
                            size="sm">
                      Run handoff
                    </Button>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        </Section>
      )}
    </div>
  );
}
